// <auto-generated />
using System;
using DonationManagement.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DonationManagement.Core.Migrations
{
    [DbContext(typeof(DonationDbContext))]
    [Migration("20260411081355_SeedRealisticData")]
    partial class SeedRealisticData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DonationManagement.Core.Entities.Case", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DonorId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SupervisorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DonorId");

                    b.HasIndex("SupervisorId");

                    b.ToTable("Cases");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Amount = 3000m,
                            CategoryId = 101,
                            Date = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "مساعدة طالب جامعي متعثر في مصاريف الكلية",
                            DonorId = 101,
                            Status = "Open",
                            SupervisorId = 1
                        },
                        new
                        {
                            Id = 102,
                            Amount = 15000m,
                            CategoryId = 102,
                            Date = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "عملية قسطرة قلب لمريض مسن",
                            DonorId = 102,
                            Status = "In Progress",
                            SupervisorId = 1
                        },
                        new
                        {
                            Id = 103,
                            Amount = 500m,
                            CategoryId = 103,
                            Date = new DateTime(2026, 1, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "شنطة غذاء لأسرة فقيرة",
                            DonorId = 103,
                            Status = "Closed",
                            SupervisorId = 1
                        },
                        new
                        {
                            Id = 104,
                            Amount = 7000m,
                            CategoryId = 104,
                            Date = new DateTime(2026, 2, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "توصيل مياه شرب لقرية نائية",
                            DonorId = 104,
                            Status = "Open",
                            SupervisorId = 1
                        },
                        new
                        {
                            Id = 105,
                            Amount = 12000m,
                            CategoryId = 105,
                            Date = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "جهاز كهربائي لتجهيز عروسة يتيمة",
                            DonorId = 105,
                            Status = "Open",
                            SupervisorId = 1
                        },
                        new
                        {
                            Id = 106,
                            Amount = 2500m,
                            CategoryId = 102,
                            Date = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "أدوية شهرية لمريض سكري",
                            DonorId = 106,
                            Status = "In Progress",
                            SupervisorId = 1
                        },
                        new
                        {
                            Id = 107,
                            Amount = 1500m,
                            CategoryId = 101,
                            Date = new DateTime(2026, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "حقائب مدرسية وعمل أنشطة لأطفال أيتام",
                            DonorId = 107,
                            Status = "Closed",
                            SupervisorId = 1
                        },
                        new
                        {
                            Id = 108,
                            Amount = 40000m,
                            CategoryId = 104,
                            Date = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "بناء سقف منزل آيل للسقوط",
                            DonorId = 108,
                            Status = "Open",
                            SupervisorId = 1
                        },
                        new
                        {
                            Id = 109,
                            Amount = 800m,
                            CategoryId = 103,
                            Date = new DateTime(2026, 3, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "دعم غذائي لأسرة من 5 أفراد",
                            DonorId = 109,
                            Status = "Closed",
                            SupervisorId = 1
                        },
                        new
                        {
                            Id = 110,
                            Amount = 6000m,
                            CategoryId = 105,
                            Date = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "مساعدة عروسين في تأسيس المنزل",
                            DonorId = 110,
                            Status = "In Progress",
                            SupervisorId = 1
                        },
                        new
                        {
                            Id = 111,
                            Amount = 3500m,
                            CategoryId = 103,
                            Date = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "ملابس شتوية للأسر المتعففة",
                            DonorId = 101,
                            Status = "Open",
                            SupervisorId = 1
                        },
                        new
                        {
                            Id = 112,
                            Amount = 20000m,
                            CategoryId = 102,
                            Date = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "عملية شفط سوائل على المخ للطفلة خديجة",
                            DonorId = 102,
                            Status = "Open",
                            SupervisorId = 1
                        },
                        new
                        {
                            Id = 113,
                            Amount = 4500m,
                            CategoryId = 104,
                            Date = new DateTime(2026, 3, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "سداد دين عن غارمين",
                            DonorId = 103,
                            Status = "In Progress",
                            SupervisorId = 1
                        },
                        new
                        {
                            Id = 114,
                            Amount = 1800m,
                            CategoryId = 101,
                            Date = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "دعم مصروفات مدارس لأسرة أيتام",
                            DonorId = 104,
                            Status = "Open",
                            SupervisorId = 1
                        },
                        new
                        {
                            Id = 115,
                            Amount = 9000m,
                            CategoryId = 105,
                            Date = new DateTime(2026, 4, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "شراء ثلاجة وغسالة لعروسة",
                            DonorId = 105,
                            Status = "Open",
                            SupervisorId = 1
                        },
                        new
                        {
                            Id = 116,
                            Amount = 1200m,
                            CategoryId = 102,
                            Date = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "تبرع لبنك الدم القومي",
                            DonorId = 106,
                            Status = "Closed",
                            SupervisorId = 1
                        },
                        new
                        {
                            Id = 117,
                            Amount = 50000m,
                            CategoryId = 104,
                            Date = new DateTime(2026, 4, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "ترميم دار إيواء للأطفال الرضع",
                            DonorId = 107,
                            Status = "In Progress",
                            SupervisorId = 1
                        },
                        new
                        {
                            Id = 118,
                            Amount = 2500m,
                            CategoryId = 103,
                            Date = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "وجبات إفطار صائم متكاملة",
                            DonorId = 108,
                            Status = "Closed",
                            SupervisorId = 1
                        },
                        new
                        {
                            Id = 119,
                            Amount = 4200m,
                            CategoryId = 101,
                            Date = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "أدوات ميكانيكا لشاب ليبدأ مشروع مستقل",
                            DonorId = 109,
                            Status = "Open",
                            SupervisorId = 1
                        },
                        new
                        {
                            Id = 120,
                            Amount = 8000m,
                            CategoryId = 102,
                            Date = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "علاج كيمائي لمرضى الحروق",
                            DonorId = 110,
                            Status = "Open",
                            SupervisorId = 1
                        });
                });

            modelBuilder.Entity("DonationManagement.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Description = "كفالة طلاب ومستلزمات دراسية",
                            Type = "تعليم"
                        },
                        new
                        {
                            Id = 102,
                            Description = "أدوية وعمليات جراحية",
                            Type = "صحة"
                        },
                        new
                        {
                            Id = 103,
                            Description = "مواد غذائية ووجبات إطعام",
                            Type = "غذاء"
                        },
                        new
                        {
                            Id = 104,
                            Description = "بناء بيوت وتوصيل مياه",
                            Type = "إعمار"
                        },
                        new
                        {
                            Id = 105,
                            Description = "مساعدة الشباب غير القادرين",
                            Type = "تجهيز عرائس"
                        });
                });

            modelBuilder.Entity("DonationManagement.Core.Entities.Distribution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DistributionDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HandledByEmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("HandledByEmployeeId");

                    b.ToTable("Distributions");
                });

            modelBuilder.Entity("DonationManagement.Core.Entities.Donor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Donors");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Email = "ahmed.a@example.com",
                            Name = "أحمد عبدالله",
                            Password = "$2a$11$/u2qj94UTkAB2m91.SYmX.WR6ShENYTBx2SK5SAKhr3RLq2Ux603W",
                            Phone = "01011112222",
                            RegisterDate = new DateTime(2025, 1, 10, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 102,
                            Email = "sara.g@example.com",
                            Name = "سارة جمال",
                            Password = "$2a$11$/u2qj94UTkAB2m91.SYmX.WR6ShENYTBx2SK5SAKhr3RLq2Ux603W",
                            Phone = "01122223333",
                            RegisterDate = new DateTime(2025, 2, 5, 12, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 103,
                            Email = "mahmoud.h@example.com",
                            Name = "محمود حسن",
                            Password = "$2a$11$/u2qj94UTkAB2m91.SYmX.WR6ShENYTBx2SK5SAKhr3RLq2Ux603W",
                            Phone = "01233334444",
                            RegisterDate = new DateTime(2025, 3, 12, 9, 15, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 104,
                            Email = "nourhan.t@example.com",
                            Name = "نورهان طارق",
                            Password = "$2a$11$/u2qj94UTkAB2m91.SYmX.WR6ShENYTBx2SK5SAKhr3RLq2Ux603W",
                            Phone = "01544445555",
                            RegisterDate = new DateTime(2025, 4, 18, 14, 45, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 105,
                            Email = "khaled.s@example.com",
                            Name = "خالد سعيد",
                            Password = "$2a$11$/u2qj94UTkAB2m91.SYmX.WR6ShENYTBx2SK5SAKhr3RLq2Ux603W",
                            Phone = "01055556666",
                            RegisterDate = new DateTime(2025, 5, 20, 16, 20, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 106,
                            Email = "yasmeen.k@example.com",
                            Name = "ياسمين كمال",
                            Password = "$2a$11$/u2qj94UTkAB2m91.SYmX.WR6ShENYTBx2SK5SAKhr3RLq2Ux603W",
                            Phone = "01166667777",
                            RegisterDate = new DateTime(2025, 6, 22, 11, 10, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 107,
                            Email = "mostafa.f@example.com",
                            Name = "مصطفى فهمي",
                            Password = "$2a$11$/u2qj94UTkAB2m91.SYmX.WR6ShENYTBx2SK5SAKhr3RLq2Ux603W",
                            Phone = "01277778888",
                            RegisterDate = new DateTime(2025, 7, 30, 8, 50, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 108,
                            Email = "raghda.s@example.com",
                            Name = "رغدة سمير",
                            Password = "$2a$11$/u2qj94UTkAB2m91.SYmX.WR6ShENYTBx2SK5SAKhr3RLq2Ux603W",
                            Phone = "01588889999",
                            RegisterDate = new DateTime(2025, 8, 14, 13, 25, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 109,
                            Email = "omar.f@example.com",
                            Name = "عمر فاروق",
                            Password = "$2a$11$/u2qj94UTkAB2m91.SYmX.WR6ShENYTBx2SK5SAKhr3RLq2Ux603W",
                            Phone = "01099990000",
                            RegisterDate = new DateTime(2025, 9, 5, 15, 55, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 110,
                            Email = "laila.a@example.com",
                            Name = "ليلى عبد الرحمن",
                            Password = "$2a$11$/u2qj94UTkAB2m91.SYmX.WR6ShENYTBx2SK5SAKhr3RLq2Ux603W",
                            Phone = "01100001111",
                            RegisterDate = new DateTime(2025, 10, 1, 10, 5, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("DonationManagement.Core.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Ismailia , Egypt",
                            Email = "12baraka34@gmail.com",
                            Name = "Ibrahim Nasser",
                            Password = "$2a$11$/u2qj94UTkAB2m91.SYmX.WR6ShENYTBx2SK5SAKhr3RLq2Ux603W",
                            Phone = "01278988474",
                            Role = "Admin",
                            Username = "Ibrahim"
                        });
                });

            modelBuilder.Entity("DonationManagement.Core.Entities.Case", b =>
                {
                    b.HasOne("DonationManagement.Core.Entities.Category", "Category")
                        .WithMany("Cases")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DonationManagement.Core.Entities.Donor", "Donor")
                        .WithMany("Cases")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DonationManagement.Core.Entities.Employee", "Supervisor")
                        .WithMany("RegisteredCases")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("Donor");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("DonationManagement.Core.Entities.Distribution", b =>
                {
                    b.HasOne("DonationManagement.Core.Entities.Case", "Case")
                        .WithMany("Distributions")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DonationManagement.Core.Entities.Employee", "HandledByEmployee")
                        .WithMany("DistributionsHandled")
                        .HasForeignKey("HandledByEmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Case");

                    b.Navigation("HandledByEmployee");
                });

            modelBuilder.Entity("DonationManagement.Core.Entities.Case", b =>
                {
                    b.Navigation("Distributions");
                });

            modelBuilder.Entity("DonationManagement.Core.Entities.Category", b =>
                {
                    b.Navigation("Cases");
                });

            modelBuilder.Entity("DonationManagement.Core.Entities.Donor", b =>
                {
                    b.Navigation("Cases");
                });

            modelBuilder.Entity("DonationManagement.Core.Entities.Employee", b =>
                {
                    b.Navigation("DistributionsHandled");

                    b.Navigation("RegisteredCases");
                });
#pragma warning restore 612, 618
        }
    }
}
