// <auto-generated />
using System;
using DonationManagement.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DonationManagement.Core.Migrations
{
    [DbContext(typeof(DonationDbContext))]
    [Migration("20260411085239_SeedRealisticEnglishData")]
    partial class SeedRealisticEnglishData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DonationManagement.Core.Entities.Case", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DonorId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SupervisorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DonorId");

                    b.HasIndex("SupervisorId");

                    b.ToTable("Cases");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Amount = 3000m,
                            CategoryId = 101,
                            Date = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sponsorship for a struggling university student",
                            DonorId = 101,
                            Status = "Open",
                            SupervisorId = 1
                        },
                        new
                        {
                            Id = 102,
                            Amount = 15000m,
                            CategoryId = 102,
                            Date = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Heart surgery for an elderly patient",
                            DonorId = 102,
                            Status = "In Progress",
                            SupervisorId = 1
                        },
                        new
                        {
                            Id = 103,
                            Amount = 500m,
                            CategoryId = 103,
                            Date = new DateTime(2026, 1, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Monthly food basket for a family in need",
                            DonorId = 103,
                            Status = "Closed",
                            SupervisorId = 1
                        },
                        new
                        {
                            Id = 104,
                            Amount = 7000m,
                            CategoryId = 104,
                            Date = new DateTime(2026, 2, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Installing a clean water well in a rural village",
                            DonorId = 104,
                            Status = "Open",
                            SupervisorId = 1
                        },
                        new
                        {
                            Id = 105,
                            Amount = 1200m,
                            CategoryId = 103,
                            Date = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Winter clothing drive for orphanages",
                            DonorId = 105,
                            Status = "Open",
                            SupervisorId = 1
                        },
                        new
                        {
                            Id = 106,
                            Amount = 2500m,
                            CategoryId = 102,
                            Date = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Monthly insulin medication for diabetic patients",
                            DonorId = 106,
                            Status = "In Progress",
                            SupervisorId = 1
                        },
                        new
                        {
                            Id = 107,
                            Amount = 1500m,
                            CategoryId = 101,
                            Date = new DateTime(2026, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "School uniforms and backpacks for 50 kids",
                            DonorId = 107,
                            Status = "Closed",
                            SupervisorId = 1
                        },
                        new
                        {
                            Id = 108,
                            Amount = 4000m,
                            CategoryId = 104,
                            Date = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Repairing the roof of a collapsed house",
                            DonorId = 108,
                            Status = "Open",
                            SupervisorId = 1
                        },
                        new
                        {
                            Id = 109,
                            Amount = 800m,
                            CategoryId = 103,
                            Date = new DateTime(2026, 3, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Emergency food supply for a refugee family",
                            DonorId = 109,
                            Status = "Closed",
                            SupervisorId = 1
                        },
                        new
                        {
                            Id = 110,
                            Amount = 6000m,
                            CategoryId = 104,
                            Date = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Furniture and basics for a newly built shelter",
                            DonorId = 110,
                            Status = "In Progress",
                            SupervisorId = 1
                        },
                        new
                        {
                            Id = 111,
                            Amount = 3500m,
                            CategoryId = 101,
                            Date = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Laptops for high-achieving low-income students",
                            DonorId = 101,
                            Status = "Open",
                            SupervisorId = 1
                        },
                        new
                        {
                            Id = 112,
                            Amount = 20000m,
                            CategoryId = 102,
                            Date = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Urgent diagnostic center for specialized tests",
                            DonorId = 102,
                            Status = "Open",
                            SupervisorId = 1
                        },
                        new
                        {
                            Id = 113,
                            Amount = 4500m,
                            CategoryId = 105,
                            Date = new DateTime(2026, 3, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Clearing debts for single mothers",
                            DonorId = 103,
                            Status = "In Progress",
                            SupervisorId = 1
                        },
                        new
                        {
                            Id = 114,
                            Amount = 1800m,
                            CategoryId = 101,
                            Date = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Online course subscriptions for skill dev",
                            DonorId = 104,
                            Status = "Open",
                            SupervisorId = 1
                        },
                        new
                        {
                            Id = 115,
                            Amount = 9000m,
                            CategoryId = 104,
                            Date = new DateTime(2026, 4, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Solar panel installation for a community center",
                            DonorId = 105,
                            Status = "Open",
                            SupervisorId = 1
                        },
                        new
                        {
                            Id = 116,
                            Amount = 1200m,
                            CategoryId = 102,
                            Date = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Wheelchairs for disabled athletes",
                            DonorId = 106,
                            Status = "Closed",
                            SupervisorId = 1
                        },
                        new
                        {
                            Id = 117,
                            Amount = 5000m,
                            CategoryId = 101,
                            Date = new DateTime(2026, 4, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Restoration of a local library",
                            DonorId = 107,
                            Status = "In Progress",
                            SupervisorId = 1
                        },
                        new
                        {
                            Id = 118,
                            Amount = 2500m,
                            CategoryId = 103,
                            Date = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Nutrition kits for pregnant women",
                            DonorId = 108,
                            Status = "Closed",
                            SupervisorId = 1
                        },
                        new
                        {
                            Id = 119,
                            Amount = 4200m,
                            CategoryId = 105,
                            Date = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Vocational training for unemployed youth",
                            DonorId = 109,
                            Status = "Open",
                            SupervisorId = 1
                        },
                        new
                        {
                            Id = 120,
                            Amount = 8000m,
                            CategoryId = 102,
                            Date = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Rehabilitation center for post-surgery recovery",
                            DonorId = 110,
                            Status = "Open",
                            SupervisorId = 1
                        });
                });

            modelBuilder.Entity("DonationManagement.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Description = "Student sponsorship and school supplies",
                            Type = "Education"
                        },
                        new
                        {
                            Id = 102,
                            Description = "Medications, surgeries, and medical equipment",
                            Type = "Healthcare"
                        },
                        new
                        {
                            Id = 103,
                            Description = "Food packages and meal distributions",
                            Type = "Food Security"
                        },
                        new
                        {
                            Id = 104,
                            Description = "Home renovation and clean water access",
                            Type = "Housing"
                        },
                        new
                        {
                            Id = 105,
                            Description = "Disaster response and urgent assistance",
                            Type = "Emergency Relief"
                        });
                });

            modelBuilder.Entity("DonationManagement.Core.Entities.Distribution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DistributionDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HandledByEmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("HandledByEmployeeId");

                    b.ToTable("Distributions");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Amount = 500m,
                            CaseId = 103,
                            DistributionDate = new DateTime(2026, 1, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            HandledByEmployeeId = 1,
                            Recipient = "Sarah Jenkins",
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 102,
                            Amount = 1500m,
                            CaseId = 107,
                            DistributionDate = new DateTime(2026, 2, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            HandledByEmployeeId = 1,
                            Recipient = "City General Hospital",
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 103,
                            Amount = 800m,
                            CaseId = 109,
                            DistributionDate = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            HandledByEmployeeId = 1,
                            Recipient = "Local Refugee Center",
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 104,
                            Amount = 5000m,
                            CaseId = 102,
                            DistributionDate = new DateTime(2026, 1, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            HandledByEmployeeId = 1,
                            Recipient = "Health Services Dept",
                            Status = "Processing"
                        },
                        new
                        {
                            Id = 105,
                            Amount = 2000m,
                            CaseId = 106,
                            DistributionDate = new DateTime(2026, 2, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            HandledByEmployeeId = 1,
                            Recipient = "Diabetic Care Clinic",
                            Status = "Completed"
                        });
                });

            modelBuilder.Entity("DonationManagement.Core.Entities.Donor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Donors");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Email = "james.w@example.com",
                            Name = "James Wilson",
                            Password = "$2a$11$/u2qj94UTkAB2m91.SYmX.WR6ShENYTBx2SK5SAKhr3RLq2Ux603W",
                            Phone = "+12025550101",
                            RegisterDate = new DateTime(2025, 1, 10, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 102,
                            Email = "mary.j@example.com",
                            Name = "Mary Johnson",
                            Password = "$2a$11$/u2qj94UTkAB2m91.SYmX.WR6ShENYTBx2SK5SAKhr3RLq2Ux603W",
                            Phone = "+12025550102",
                            RegisterDate = new DateTime(2025, 2, 5, 12, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 103,
                            Email = "robert.s@example.com",
                            Name = "Robert Smith",
                            Password = "$2a$11$/u2qj94UTkAB2m91.SYmX.WR6ShENYTBx2SK5SAKhr3RLq2Ux603W",
                            Phone = "+12025550103",
                            RegisterDate = new DateTime(2025, 3, 12, 9, 15, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 104,
                            Email = "patricia.b@example.com",
                            Name = "Patricia Brown",
                            Password = "$2a$11$/u2qj94UTkAB2m91.SYmX.WR6ShENYTBx2SK5SAKhr3RLq2Ux603W",
                            Phone = "+12025550104",
                            RegisterDate = new DateTime(2025, 4, 18, 14, 45, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 105,
                            Email = "michael.d@example.com",
                            Name = "Michael Davis",
                            Password = "$2a$11$/u2qj94UTkAB2m91.SYmX.WR6ShENYTBx2SK5SAKhr3RLq2Ux603W",
                            Phone = "+12025550105",
                            RegisterDate = new DateTime(2025, 5, 20, 16, 20, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 106,
                            Email = "linda.m@example.com",
                            Name = "Linda Miller",
                            Password = "$2a$11$/u2qj94UTkAB2m91.SYmX.WR6ShENYTBx2SK5SAKhr3RLq2Ux603W",
                            Phone = "+12025550106",
                            RegisterDate = new DateTime(2025, 6, 22, 11, 10, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 107,
                            Email = "david.t@example.com",
                            Name = "David Taylor",
                            Password = "$2a$11$/u2qj94UTkAB2m91.SYmX.WR6ShENYTBx2SK5SAKhr3RLq2Ux603W",
                            Phone = "+12025550107",
                            RegisterDate = new DateTime(2025, 7, 30, 8, 50, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 108,
                            Email = "elizabeth.a@example.com",
                            Name = "Elizabeth Anderson",
                            Password = "$2a$11$/u2qj94UTkAB2m91.SYmX.WR6ShENYTBx2SK5SAKhr3RLq2Ux603W",
                            Phone = "+12025550108",
                            RegisterDate = new DateTime(2025, 8, 14, 13, 25, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 109,
                            Email = "richard.t@example.com",
                            Name = "Richard Thomas",
                            Password = "$2a$11$/u2qj94UTkAB2m91.SYmX.WR6ShENYTBx2SK5SAKhr3RLq2Ux603W",
                            Phone = "+12025550109",
                            RegisterDate = new DateTime(2025, 9, 5, 15, 55, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 110,
                            Email = "barbara.j@example.com",
                            Name = "Barbara Jackson",
                            Password = "$2a$11$/u2qj94UTkAB2m91.SYmX.WR6ShENYTBx2SK5SAKhr3RLq2Ux603W",
                            Phone = "+12025550110",
                            RegisterDate = new DateTime(2025, 10, 1, 10, 5, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("DonationManagement.Core.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Ismailia, Egypt",
                            Email = "12baraka34@gmail.com",
                            Name = "Ibrahim Nasser",
                            Password = "$2a$11$/u2qj94UTkAB2m91.SYmX.WR6ShENYTBx2SK5SAKhr3RLq2Ux603W",
                            Phone = "01278988474",
                            Role = "Admin",
                            Username = "Ibrahim"
                        },
                        new
                        {
                            Id = 2,
                            Address = "New York, USA",
                            Email = "sarah.c@example.com",
                            Name = "Sarah Connor",
                            Password = "$2a$11$/u2qj94UTkAB2m91.SYmX.WR6ShENYTBx2SK5SAKhr3RLq2Ux603W",
                            Phone = "+12025550199",
                            Role = "Supervisor",
                            Username = "SarahC"
                        },
                        new
                        {
                            Id = 3,
                            Address = "London, UK",
                            Email = "john.doe@example.com",
                            Name = "John Doe",
                            Password = "$2a$11$/u2qj94UTkAB2m91.SYmX.WR6ShENYTBx2SK5SAKhr3RLq2Ux603W",
                            Phone = "+12025550188",
                            Role = "FieldWorker",
                            Username = "JohnD"
                        });
                });

            modelBuilder.Entity("DonationManagement.Core.Entities.Case", b =>
                {
                    b.HasOne("DonationManagement.Core.Entities.Category", "Category")
                        .WithMany("Cases")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DonationManagement.Core.Entities.Donor", "Donor")
                        .WithMany("Cases")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DonationManagement.Core.Entities.Employee", "Supervisor")
                        .WithMany("RegisteredCases")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("Donor");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("DonationManagement.Core.Entities.Distribution", b =>
                {
                    b.HasOne("DonationManagement.Core.Entities.Case", "Case")
                        .WithMany("Distributions")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DonationManagement.Core.Entities.Employee", "HandledByEmployee")
                        .WithMany("DistributionsHandled")
                        .HasForeignKey("HandledByEmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Case");

                    b.Navigation("HandledByEmployee");
                });

            modelBuilder.Entity("DonationManagement.Core.Entities.Case", b =>
                {
                    b.Navigation("Distributions");
                });

            modelBuilder.Entity("DonationManagement.Core.Entities.Category", b =>
                {
                    b.Navigation("Cases");
                });

            modelBuilder.Entity("DonationManagement.Core.Entities.Donor", b =>
                {
                    b.Navigation("Cases");
                });

            modelBuilder.Entity("DonationManagement.Core.Entities.Employee", b =>
                {
                    b.Navigation("DistributionsHandled");

                    b.Navigation("RegisteredCases");
                });
#pragma warning restore 612, 618
        }
    }
}
