// <auto-generated />
using System;
using DonationManagement.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DonationManagement.Core.Migrations
{
    [DbContext(typeof(DonationDbContext))]
    [Migration("20260416155425_FreshStart")]
    partial class FreshStart
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DonationManagement.Core.Entities.Case", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SupervisorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SupervisorId");

                    b.ToTable("Cases");

                    b.HasData(
                        new
                        {
                            Id = 201,
                            Address = "Detroit, USA",
                            CategoryId = 102,
                            Description = "Needs a new wheelchair for educational mobility",
                            Name = "Alice Peterson",
                            Phone = "+12025550501",
                            RegistDate = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Approved",
                            SupervisorId = 2
                        },
                        new
                        {
                            Id = 202,
                            Address = "Houston, USA",
                            CategoryId = 103,
                            Description = "Monthly food support for a family of 6",
                            Name = "Robert's Family",
                            Phone = "+12025550502",
                            RegistDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Pending Review",
                            SupervisorId = 2
                        },
                        new
                        {
                            Id = 203,
                            Address = "Nairobi, Kenya",
                            CategoryId = 104,
                            Description = "Roof repairs for the main dormitory",
                            Name = "St. Paul Orphanage",
                            Phone = "+12025550503",
                            RegistDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Approved",
                            SupervisorId = 2
                        });
                });

            modelBuilder.Entity("DonationManagement.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Description = "Student sponsorship and school supplies",
                            Type = "Education"
                        },
                        new
                        {
                            Id = 102,
                            Description = "Medications, surgeries, and medical equipment",
                            Type = "Healthcare"
                        },
                        new
                        {
                            Id = 103,
                            Description = "Food packages and meal distributions",
                            Type = "Food Security"
                        },
                        new
                        {
                            Id = 104,
                            Description = "Home renovation and clean water access",
                            Type = "Housing"
                        },
                        new
                        {
                            Id = 105,
                            Description = "Disaster response and urgent assistance",
                            Type = "Emergency Relief"
                        });
                });

            modelBuilder.Entity("DonationManagement.Core.Entities.Distribution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DistributionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DonationId")
                        .HasColumnType("int");

                    b.Property<int?>("HandledByEmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("DonationId");

                    b.HasIndex("HandledByEmployeeId");

                    b.ToTable("Distributions");

                    b.HasData(
                        new
                        {
                            Id = 401,
                            Amount = 3000m,
                            CaseId = 201,
                            DistributionDate = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DonationId = 301,
                            HandledByEmployeeId = 3,
                            Notes = "Funding provided for wheelchair procurement",
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 402,
                            Amount = 500m,
                            CaseId = 202,
                            DistributionDate = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            DonationId = 302,
                            HandledByEmployeeId = 3,
                            Notes = "First monthly food basket distribution",
                            Status = "Completed"
                        });
                });

            modelBuilder.Entity("DonationManagement.Core.Entities.Donation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DonorId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SupervisorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DonorId");

                    b.HasIndex("SupervisorId");

                    b.ToTable("Donations");

                    b.HasData(
                        new
                        {
                            Id = 301,
                            Amount = 5000m,
                            CategoryId = 102,
                            Date = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Annual CSR contribution for Healthcare",
                            DonorId = 103,
                            Status = "Completed",
                            SupervisorId = 2
                        },
                        new
                        {
                            Id = 302,
                            Amount = 1000m,
                            CategoryId = 103,
                            Date = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Personal gift for food drive",
                            DonorId = 101,
                            Status = "Completed",
                            SupervisorId = 2
                        },
                        new
                        {
                            Id = 303,
                            Amount = 2500m,
                            CategoryId = 105,
                            Date = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Emergency relief fund contribution",
                            DonorId = 102,
                            Status = "Pending",
                            SupervisorId = 2
                        });
                });

            modelBuilder.Entity("DonationManagement.Core.Entities.Donor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Donors");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Address = "Los Angeles, USA",
                            Email = "james.w@example.com",
                            Name = "James Wilson",
                            Password = "$2a$11$/u2qj94UTkAB2m91.SYmX.WR6ShENYTBx2SK5SAKhr3RLq2Ux603W",
                            Phone = "+12025550101",
                            RegisterDate = new DateTime(2025, 1, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            Type = "Individual"
                        },
                        new
                        {
                            Id = 102,
                            Address = "Chicago, USA",
                            Email = "mary.j@example.com",
                            Name = "Mary Johnson",
                            Password = "$2a$11$/u2qj94UTkAB2m91.SYmX.WR6ShENYTBx2SK5SAKhr3RLq2Ux603W",
                            Phone = "+12025550102",
                            RegisterDate = new DateTime(2025, 2, 5, 12, 30, 0, 0, DateTimeKind.Utc),
                            Type = "Individual"
                        },
                        new
                        {
                            Id = 103,
                            Address = "San Francisco, USA",
                            Email = "donations@globaltech.com",
                            Name = "Global Tech Corp",
                            Password = "$2a$11$/u2qj94UTkAB2m91.SYmX.WR6ShENYTBx2SK5SAKhr3RLq2Ux603W",
                            Phone = "+12025550300",
                            RegisterDate = new DateTime(2025, 3, 12, 9, 15, 0, 0, DateTimeKind.Utc),
                            Type = "Corporate"
                        });
                });

            modelBuilder.Entity("DonationManagement.Core.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Ismailia, Egypt",
                            Email = "12baraka34@gmail.com",
                            Name = "Ibrahim Nasser",
                            Password = "$2a$11$/u2qj94UTkAB2m91.SYmX.WR6ShENYTBx2SK5SAKhr3RLq2Ux603W",
                            Phone = "01278988474",
                            Role = "Admin",
                            Username = "Ibrahim"
                        },
                        new
                        {
                            Id = 2,
                            Address = "New York, USA",
                            Email = "sarah.c@example.com",
                            Name = "Sarah Connor",
                            Password = "$2a$11$/u2qj94UTkAB2m91.SYmX.WR6ShENYTBx2SK5SAKhr3RLq2Ux603W",
                            Phone = "+12025550199",
                            Role = "Supervisor",
                            Username = "SarahC"
                        },
                        new
                        {
                            Id = 3,
                            Address = "London, UK",
                            Email = "john.doe@example.com",
                            Name = "John Doe",
                            Password = "$2a$11$/u2qj94UTkAB2m91.SYmX.WR6ShENYTBx2SK5SAKhr3RLq2Ux603W",
                            Phone = "+12025550188",
                            Role = "FieldWorker",
                            Username = "JohnD"
                        });
                });

            modelBuilder.Entity("DonationManagement.Core.Entities.Case", b =>
                {
                    b.HasOne("DonationManagement.Core.Entities.Category", "Category")
                        .WithMany("Cases")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DonationManagement.Core.Entities.Employee", "Supervisor")
                        .WithMany("CasesRegistered")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("DonationManagement.Core.Entities.Distribution", b =>
                {
                    b.HasOne("DonationManagement.Core.Entities.Case", "Case")
                        .WithMany("Distributions")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DonationManagement.Core.Entities.Donation", "Donation")
                        .WithMany("Distributions")
                        .HasForeignKey("DonationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DonationManagement.Core.Entities.Employee", "HandledByEmployee")
                        .WithMany("DistributionsHandled")
                        .HasForeignKey("HandledByEmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Case");

                    b.Navigation("Donation");

                    b.Navigation("HandledByEmployee");
                });

            modelBuilder.Entity("DonationManagement.Core.Entities.Donation", b =>
                {
                    b.HasOne("DonationManagement.Core.Entities.Category", "Category")
                        .WithMany("Donations")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DonationManagement.Core.Entities.Donor", "Donor")
                        .WithMany("Donations")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DonationManagement.Core.Entities.Employee", "Supervisor")
                        .WithMany("DonationsRegistered")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("Donor");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("DonationManagement.Core.Entities.Case", b =>
                {
                    b.Navigation("Distributions");
                });

            modelBuilder.Entity("DonationManagement.Core.Entities.Category", b =>
                {
                    b.Navigation("Cases");

                    b.Navigation("Donations");
                });

            modelBuilder.Entity("DonationManagement.Core.Entities.Donation", b =>
                {
                    b.Navigation("Distributions");
                });

            modelBuilder.Entity("DonationManagement.Core.Entities.Donor", b =>
                {
                    b.Navigation("Donations");
                });

            modelBuilder.Entity("DonationManagement.Core.Entities.Employee", b =>
                {
                    b.Navigation("CasesRegistered");

                    b.Navigation("DistributionsHandled");

                    b.Navigation("DonationsRegistered");
                });
#pragma warning restore 612, 618
        }
    }
}
